# Inleiding

Bij de opmaak van een toelatingsaanvraag of archeologienota wordt steeds de afweging gemaakt of een vooronderzoek op het terrein moet uitgevoerd worden. Dit kan uiteraard afhankelijk zijn van allerlei factoren, bijvoorbeeld de mate van verstoring van een projectgebied, de geomorfologische context, enz. Op die manier wordt steeds, voor alle archeologische periodes, een inschatting gemaakt van het potentieel van de aanwezigheid van archeologische sites, sporen en vondsten, en het 'kennispotentieel' hiervan bij het uitvoeren van verder onderzoek.

Dit proces doorloopt verschillende stappen, gaande van een bureauonderzoek, naar een eventueel landschappelijk (bodem)onderzoek, tot prospectie met ingreep in de bodem. Dit laatste kan bestaan uit archeologisch booronderzoek en/of proefputten in functie van steentijdarcheologie, en proefsleuven en kijkvensters in functie van alle recentere perioden. Bij steentijdsites wordt de prospectie vaak opgedeeld in twee fasen: de eigenlijke prospectie en, indien deze positief is, waardering.

De aanzet van een dergelijk traject is het bepalen van een 'verwachting' ten aanzien van de aanwezigheid van steentijdsites. De huidige praktijk wijkt hier immers af van vooronderzoek naar zogenaamde 'sporensites'. Bij deze laatsten wordt steeds geredeneerd vanuit de verwachting van de [afwezigheid]{.underline} van een potentieel op kenniswinst: er wordt geen verder onderzoek verricht wanneer de vermoedelijke afwezigheid van een site met hoge waarschijnlijkheid kan aangetoond worden, of de potentiële kenniswinst ervan niet opweegt tegen de onderzoekskosten. Voor steentijd artefactensites is de redenering in de huidige praktijk doorgaans omgekeerd: er wordt meestal alleen een specifiek steentijdtraject opgestart wanneer de verwachting naar de [aanwezigheid]{.underline} van sites met potentieel op kenniswinst hoog is.

Het bepalen van die verwachting naar de aanwezigheid van steentijdsites is echter niet eenvoudig. Het samenspel tussen de archeologische en antropologische aspecten enerzijds, en de landschappelijke context anderzijds, biedt een zeer grote variatie aan mogelijke situaties. Een recent onderzoek naar de huidige praktijk terzake in de preventieve archeologie wees dan ook op een grote diversiteit in aanpak en gebruik van selectiecriteria[^inleiding-1]. Naast de problematiek van het onderzoek van prehistorische jager-verzamelaarsgemeenschappen en de specifieke economische, sociale, en culturele aspecten hieromtrent, speelt ook de (paleo)landschappelijke context een grote rol. De landschappen en bodems zijn sinds de prehistorie immers vaak ingrijpend veranderd.

[^inleiding-1]: Van Baelen *et al.* 2022.

Daarom eist steentijdarcheologie een zeer specifieke expertise en ervaring. Een goed inzicht in de landschappelijke processen is daarbij heel belangrijk, enerzijds voor het 'lezen' van het landschap en de plaats van de prehistorische mens hierin, anderzijds voor het inschatten van de aard en impact van tafonomische processen op het bodemarchief (erosie, sedimentatie, bodemvorming, ...). In dit afwegingskader komt dit aspect dan ook ruim aan bod, onderverdeeld naar de verschillende archeoregio's.

Verder biedt dit afwegingskader een overzicht van de methoden die kunnen ingezet worden bij vooronderzoek naar steentijd artefactensites, geordend per onderzoeksfase. Booronderzoek komt hierbij ruim aan bod, maar ook de andere mogelijke technieken zoals profiel- en proefputten. De Code van Goede Praktijk (CGP) omschrijft de doelstellingen van deze onderzoeken en de middelen die er minimaal voor moeten aangewend worden. Hier vullen we dit aan met een inzicht in het waarom hierachter, wat we verklaren vanuit de aard van de sites, het landschap, en de mogelijkheden en beperkingen van de verschillende methoden. Daarnaast bevat dit document meer details over de praktische uitvoeringwijze. Hieruit kan je putten om de beste onderzoeksstrategie samen te stellen voor jouw projecten, die je natuurlijk steeds aanpast aan de specifieke onderzoeksvragen, landschappelijke context en praktische omstandigheden.

Dit afwegingskader reflecteert de huidige praktijk. Naast de effectiviteit van de verschillende methoden wordt ook rekening gehouden met het kostenplaatje en de efficiëntie. We blijven ook binnen het huidige beheers- en beleidskader. Dit document is dan ook geen manifest over de ideale werkwijze, maar wil vooral de archeoloog helpen om binnen de huidige praktijk goede keuzes te maken.

De klankbordgroep formuleerde heel wat opmerkingen die verband houden met zowel de context van de huidige praktijk als de stand van zaken van het methodologisch onderzoek. Deze opmerkingen konden niet binnen het opzet van dit afwegingskader opgenomen worden, maar tonen dat sommige keuzes binnen de huidige praktijk een ideale werkwijze verhinderen, en dat de methodiek in de toekomst zeker verder moet verfijnd en beter onderbouwd worden. Onder invloed van voortschrijdend inzicht of bij uitzonderlijke omstandigheden kan dan ook van dit document afgeweken worden, uiteraard in zoverre de CGP dit toelaat.
