# Besluit

Er bestaat geen eenvoudige standaardaanpak voor vooronderzoek naar steentijd artefactensites die altijd en overal de beste resultaten biedt. We beschikken wel over een reeks bronnen, technieken en strategieën die je kan inzetten om de verschillende onderzoeksvragen te beantwoorden, doorheen een fasering van bureauonderzoek tot opgraving. Door de grote variatie in sites en regio's moet je voor elk project opnieuw de meest geschikte technieken selecteren en daarmee een onderzoekstrategie uitstippelen. Dat doe je op basis van de archeologische en landschappelijke context van het onderzoeksgebied, en de onderzoeksvragen die zich van daaruit stellen. Daarnaast moet je rekening houden met de praktische omstandigheden, en wil je natuurlijk zo kostenefficiënt[^besluit-1] mogelijk werken. Het is bovendien belangrijk om steeds ruimte voor flexibiliteit te houden in de onderzoekstrategie. Voortschrijdend inzicht tijdens het onderzoek of veranderende omstandigheden kunnen immers een verandering van je aanpak vereisen.

[^besluit-1]: 'Kost' moet hier in de brede zin begrepen worden: financieel, tijd, arbeidsomstandigheden, enz.

Doorheen elk project maak je dus een aantal keuzes die je aanpak bepalen, en daarmee ook de onderzoeksresultaten. Het is belangrijk om die keuzes expliciet te beschrijven in de rapportage, en vooral om deze ook duidelijk te motiveren. Op die manier kan de lezer niet alleen begrijpen wat je hebt gedaan, maar ook waarom.

Door de verschillende aard van de sites (mobiele artefacten versus sporen) vereist vooronderzoek naar steentijd artefactensites andere technieken dan onderzoek naar recentere perioden (boringen en putten versus sleuven). Bij preventieve archeologische projecten moet je beiden inpassen in de algemene onderzoeksstrategie en -fasering voor het projectgebied. Hiertoe moet je vanaf het bureauonderzoek rekening houden met de mogelijke aanwezigheid van alle perioden. Dit alles vraagt uiteraard een zekere inspanning en kost. Onze kennis van ons vroegste verleden vertoont echter nog zoveel hiaten, en er zijn nog zoveel onbeantwoorde onderzoeksvragen[^besluit-2], dat deze investering zeker de moeite zal lonen.

[^besluit-2]: Ryssaert *et al.* 2021; Noens *et al.* 2021.
