project:
  type: book
  output-dir: docs

execute:
  echo: false

lang: nl

book:
  title: "Afwegingskader booronderzoek"
  author: 
    - Erwin Meylemans [![](https://orcid.org/sites/default/files/images/orcid_16x16.png)](https://orcid.org/0000-0002-7544-0794) 
    - Marijn Van Gils [![](https://orcid.org/sites/default/files/images/orcid_16x16.png)](https://orcid.org/0000-0002-7516-1189)
  date: today
  cover-image: figuren/cover.png
  # collapse-level: 2
  sharing: [twitter, facebook, linkedin]
  twitter-card:
    image: "/docs/figuren/image217.jpeg"
  repo-url: https://github.com/hanecakr/handleidingBooronderzoek/
  repo-actions: [edit]
  google-analytics:
   tracking-id: "G-WFNTWBH9Q4"
  chapters:
    - index.qmd
    - updates.qmd
    - 01_inleiding.qmd
    - 02_bureauonderzoek.qmd
    - 03_landschappelijk.qmd
    - 04_prospectie.qmd
    - 05_waardering.qmd
    - 06_fasering.qmd
    - 07_besluit.qmd
    - literatuur.qmd
    
title-block-banner: "#914f9a"

    
crossref:
  fig-title: Figuur
  fig-prefix: fig.
  
language:
  toc-title-document: "Op deze pagina"
  search-no-results-text: "Geen resultaat"
  repo-action-links-edit: "Bewerk deze pagina"
  title-block-author-plural: "auteurs"
  title-block-published: "laatste update"

format:
  html:
    theme: 
      light: 
        - cosmo
        - mycss.css
      dark: 
        - slate
        - mycss.css
    cover-image: figuren/cover.png
    toc-depth: 4
