project:
  type: book
  output-dir: docs

execute:
  echo: false

lang: nl

book:
  title: "Afwegingskader booronderzoek"
  subtitle: "Vooronderzoek naar artefactensites uit de steentijd: methodiek en afwegingen"
  author: 
    - name: Erwin Meylemans
      orcid: 0000-0002-7544-0794
      affiliations: "erfgoedonderzoeker <br> agentschap Onroerend Erfgoed"

    - name: Marijn Van Gils
      orcid: 0000-0002-7516-1189
      affiliations: "erfgoedonderzoeker <br> agentschap Onroerend Erfgoed"

  publisher: "agentschap Onroerend Erfgoed"
  date: today
  cover-image: figuren/cover.png
  sharing: [twitter, facebook, linkedin]
  twitter-card:
    image: "/docs/figuren/image217.jpeg"
  repo-url: https://github.com/ErfgoedPublicaties/AKOE-11-Booronderzoek
  repo-actions: [edit]
  google-analytics:
   tracking-id: "G-WFNTWBH9Q4"
  chapters:
    - index.qmd
    - updates.qmd
    - 01_inleiding.qmd
    - 02_bureauonderzoek.qmd
    - 03_landschappelijk.qmd
    - 04_prospectie.qmd
    - 05_waardering.qmd
    - 06_fasering.qmd
    - 07_besluit.qmd
    - literatuur.qmd
    
title-block-banner: "#914f9a"
title-block-banner-color: "#FFFFFF"

crossref:
  fig-title: Figuur
  fig-prefix: fig.
  
language:
  toc-title-document: "Op deze pagina"
  search-no-results-text: "Geen resultaat"
  repo-action-links-edit: "Bewerk deze pagina"
  title-block-author-plural: "auteurs"
  title-block-published: "laatste update"

format:
  html:
    theme:
      light:
        - cosmo
        - mycss.css
      dark:
        - slate
        - mycss.css
    cover-image: figuren/cover.png
    toc-depth: 4
    link-external-newwindow: true